-- MySQL Script generated by MySQL Workbench
-- Wed Oct  3 15:15:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IntelligentAnnotationSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IntelligentAnnotationSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IntelligentAnnotationSystem` DEFAULT CHARACTER SET utf8 ;
USE `IntelligentAnnotationSystem` ;

-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(200) NOT NULL COMMENT '密码',
  `email` VARCHAR(45) NOT NULL COMMENT '邮箱',
  `phone` VARCHAR(45) NOT NULL COMMENT '手机',
  `group` INT NOT NULL COMMENT '用户组',
  `is_del` INT NOT NULL COMMENT '状态',
  `nickname` VARCHAR(45) NOT NULL COMMENT '昵称',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册日期',
  `personas` VARCHAR(45) NOT NULL COMMENT '用户画像',
  `token` VARCHAR(45) NOT NULL COMMENT 'token',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户信息存储表';


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` VARCHAR(45) NOT NULL COMMENT '标题',
  `file_path` VARCHAR(200) NOT NULL COMMENT '文件路径',
  `image_path` VARCHAR(200) NULL COMMENT '封面路径',
  `state` INT NOT NULL COMMENT '状态 0=正常 1=清除',
  `author` VARCHAR(45) NOT NULL COMMENT '作者',
  `uploader` INT NOT NULL COMMENT '上传人',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上传日期',
  PRIMARY KEY (`id`),
  INDEX `fk_article_user_idx` (`uploader` ASC),
  CONSTRAINT `fk_article_user`
    FOREIGN KEY (`uploader`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`article_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`article_history` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` INT NOT NULL COMMENT '类型 0=历史纪录 1=点赞 2=收藏',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日期',
  `article_id` INT NOT NULL COMMENT '文章id',
  `user_id` INT NOT NULL COMMENT '用户id',
  PRIMARY KEY (`id`),
  INDEX `fk_article_history_article1_idx` (`article_id` ASC),
  INDEX `fk_article_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_article_history_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `IntelligentAnnotationSystem`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`postil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`postil` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `content` VARCHAR(400) NOT NULL COMMENT '内容',
  `start` INT NOT NULL COMMENT '开始处',
  `end` INT NOT NULL COMMENT '结束处',
  `type` INT NOT NULL COMMENT '种类',
  `article_id` INT NOT NULL COMMENT '文章id',
  `user_id` INT NOT NULL COMMENT '用户id',
  `state` INT NOT NULL COMMENT '状态 0=正常 1=删除',
  PRIMARY KEY (`id`),
  INDEX `fk_postil_article1_idx` (`article_id` ASC),
  INDEX `fk_postil_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_postil_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `IntelligentAnnotationSystem`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postil_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`article_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`article_tag` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(45) NOT NULL COMMENT 'tag名字',
  `weight` VARCHAR(45) NOT NULL COMMENT '权重',
  `article_id` INT NOT NULL COMMENT '文章id',
  PRIMARY KEY (`id`),
  INDEX `fk_article_tag_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_article_tag_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `IntelligentAnnotationSystem`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`postil_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`postil_comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `content` VARCHAR(200) NOT NULL COMMENT '内容',
  `state` INT NOT NULL COMMENT '状态 0=正常 1=删除',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论日期',
  `postil_id` INT NOT NULL COMMENT '批注id',
  `user_id` INT NOT NULL COMMENT '用户id',
  `previous` INT NULL COMMENT '上一级评论',
  PRIMARY KEY (`id`),
  INDEX `fk_postil_comment_postil1_idx` (`postil_id` ASC),
  INDEX `fk_postil_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_postil_comment_postil_comment1_idx` (`previous` ASC),
  CONSTRAINT `fk_postil_comment_postil1`
    FOREIGN KEY (`postil_id`)
    REFERENCES `IntelligentAnnotationSystem`.`postil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postil_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postil_comment_postil_comment1`
    FOREIGN KEY (`previous`)
    REFERENCES `IntelligentAnnotationSystem`.`postil_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`article_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`article_comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `content` VARCHAR(200) NOT NULL COMMENT '内容',
  `state` INT NOT NULL COMMENT '状态 0=正常 1=清除',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论日期',
  `user_id` INT NOT NULL COMMENT '用户id',
  `article_id` INT NOT NULL COMMENT '文章id',
  `previous` INT NULL COMMENT '上一级评论',
  PRIMARY KEY (`id`),
  INDEX `fk_postil_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_article_comment_article1_idx` (`article_id` ASC),
  INDEX `fk_article_comment_article_comment1_idx` (`previous` ASC),
  CONSTRAINT `fk_postil_comment_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_comment_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `IntelligentAnnotationSystem`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_comment_article_comment1`
    FOREIGN KEY (`previous`)
    REFERENCES `IntelligentAnnotationSystem`.`article_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`postil_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`postil_history` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` INT NOT NULL COMMENT '种类 0=历史记录 1=点赞 2=收藏',
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日期',
  `postil_id` INT NOT NULL COMMENT '批注id',
  `user_id` INT NOT NULL COMMENT '用户id',
  PRIMARY KEY (`id`),
  INDEX `fk_postil_history_postil1_idx` (`postil_id` ASC),
  INDEX `fk_postil_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_postil_history_postil1`
    FOREIGN KEY (`postil_id`)
    REFERENCES `IntelligentAnnotationSystem`.`postil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postil_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IntelligentAnnotationSystem`.`comment_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IntelligentAnnotationSystem`.`comment_history` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `user_id` INT NOT NULL COMMENT '用户id',
  `postil_comment_id` INT NULL COMMENT '批注评论id',
  `article_comment_id` INT NULL COMMENT '文章评论id',
  PRIMARY KEY (`id`),
  INDEX `fk_comment_history_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_history_postil_comment1_idx` (`postil_comment_id` ASC),
  INDEX `fk_comment_history_article_comment1_idx` (`article_comment_id` ASC),
  CONSTRAINT `fk_comment_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `IntelligentAnnotationSystem`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_history_postil_comment1`
    FOREIGN KEY (`postil_comment_id`)
    REFERENCES `IntelligentAnnotationSystem`.`postil_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_history_article_comment1`
    FOREIGN KEY (`article_comment_id`)
    REFERENCES `IntelligentAnnotationSystem`.`article_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
